### ISSUE TITLE
java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device

### ISSUE THREAD

**Issue by Tobibur** [googlecodelabs/cosu#15]
I am getting this error on my device (API 23), which I removed all accounts and also did the factory reset.
But on the emulator, this error is not there. Is this a device issue?
### adb command
```
adb shell dpm set-device-owner com.google.codelabs.cosu/.DeviceAdminReceiver
```
### The error
```
java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device
        at android.os.Parcel.readException(Parcel.java:1607)
        at android.os.Parcel.readException(Parcel.java:1552)
        at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDevicePolicyManager.java:3515)
        at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:114)
        at com.android.commands.dpm.Dpm.onRun(Dpm.java:82)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
        at com.android.commands.dpm.Dpm.main(Dpm.java:38)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:306)
```

**Comment by amiyo-biswas** [comment]
Facing same problem.

**Comment by amiyo-biswas** [comment]
You should remove accounts from Phone.

**Comment by vishalguptahmh** [comment]
first run this 

`adb shell dpm remove-active-admin com.google.codelabs.cosu/.DeviceAdminReceiver
`

then run 

`adb shell dpm set-device-owner com.google.codelabs.cosu/.DeviceAdminReceiver`

this helps to set my device to `device owner mode`.

**Comment by Tobibur** [comment]
I had fixed the issue by formatting the device but removing any accounts on the device does the job. 
@vishalguptahmh that command didn't work when i tested it.
