### ISSUE TITLE
Unexpected @ProvisioningPreCondition

### ISSUE THREAD

**Issue by amiyo-biswas** [googlecodelabs/cosu#17]
I am getting **Unexpected @ProvisioningPreCondition** error on some devices (API 28) when set ` adb shell dpm set-device-owner` .
Does any guys meet this issue? Any help would be greatly appreciated.

`adb shell dpm set-device-owner com.myapp/.AppAdminReceiver`

### Error Is 
```
java.lang.IllegalStateException: Unexpected @ProvisioningPreCondition 99
        at android.os.Parcel.createException(Parcel.java:1974)
        at android.os.Parcel.readException(Parcel.java:1934)
        at android.os.Parcel.readException(Parcel.java:1884)
        at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDevicePolicyManager.java:5863)
        at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:176)
        at com.android.commands.dpm.Dpm.onRun(Dpm.java:106)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
        at com.android.commands.dpm.Dpm.main(Dpm.java:41)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:416)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:8007)
        at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:7291)
```

**Comment by skywalkerhbz** [comment]
Hello , I meet the same problem on a oppo euqipment also api 28. Excuse me , do you solve this problem in the end? Appreciately!

**Comment by VeluFi** [comment]
i meet the same issue on realme c2 mobile. how to solve this issue??

**Comment by mangoid** [comment]
Hi , I meet the same problem on oppo a9 . If you solve this problem，Please tell me by reddreamlove@gmail.com . Appreciately!

**Comment by aaazzz** [comment]
I am facing the same problem.
The device I'm using is REALME C3.
